### ISSUE TITLE
pod spec lint -> xcode 10.2

### ISSUE THREAD

**Issue by stefanrenne** [CocoaPods/fourflusher#18]
Whenever I run `pod spec lint` I get this output:

```
ERROR | [iOS] unknown: Encountered an unknown error (Could not find a `ios` simulator (valid values: com.apple.coresimulator.simruntime.ios-12-1, com.apple.coresimulator.simruntime.ios-12-2, com.apple.coresimulator.simruntime.tvos-12-2, com.apple.coresimulator.simruntime.watchos-5-2). Ensure that Xcode -> Window -> Devices has at least one `ios` simulator listed or otherwise add one.) during validation.
```

While there are multiple devices available with ios 12.2

```
$ xcrun simctl list
== Device Types ==
iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s)
iPhone 5 (com.apple.CoreSimulator.SimDeviceType.iPhone-5)
iPhone 5s (com.apple.CoreSimulator.SimDeviceType.iPhone-5s)
iPhone 6 (com.apple.CoreSimulator.SimDeviceType.iPhone-6)
iPhone 6 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus)
iPhone 6s (com.apple.CoreSimulator.SimDeviceType.iPhone-6s)
iPhone 6s Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus)
iPhone 7 (com.apple.CoreSimulator.SimDeviceType.iPhone-7)
iPhone 7 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-7-Plus)
iPhone 8 (com.apple.CoreSimulator.SimDeviceType.iPhone-8)
iPhone 8 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-8-Plus)
iPhone SE (com.apple.CoreSimulator.SimDeviceType.iPhone-SE)
iPhone X (com.apple.CoreSimulator.SimDeviceType.iPhone-X)
iPhone Xs (com.apple.CoreSimulator.SimDeviceType.iPhone-XS)
iPhone Xs Max (com.apple.CoreSimulator.SimDeviceType.iPhone-XS-Max)
iPhone Xʀ (com.apple.CoreSimulator.SimDeviceType.iPhone-XR)
iPad mini (5th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-mini--5th-generation-)
iPad Air (3rd generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Air--3rd-generation-)
iPad 2 (com.apple.CoreSimulator.SimDeviceType.iPad-2)
iPad Retina (com.apple.CoreSimulator.SimDeviceType.iPad-Retina)
iPad Air (com.apple.CoreSimulator.SimDeviceType.iPad-Air)
iPad mini 2 (com.apple.CoreSimulator.SimDeviceType.iPad-mini-2)
iPad mini 3 (com.apple.CoreSimulator.SimDeviceType.iPad-mini-3)
iPad mini 4 (com.apple.CoreSimulator.SimDeviceType.iPad-mini-4)
iPad Air 2 (com.apple.CoreSimulator.SimDeviceType.iPad-Air-2)
iPad (5th generation) (com.apple.CoreSimulator.SimDeviceType.iPad--5th-generation-)
iPad Pro (9.7-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--9-7-inch-)
iPad Pro (12.9-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro)
iPad Pro (12.9-inch) (2nd generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---2nd-generation-)
iPad Pro (10.5-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--10-5-inch-)
iPad (6th generation) (com.apple.CoreSimulator.SimDeviceType.iPad--6th-generation-)
iPad Pro (11-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--11-inch-)
iPad Pro (12.9-inch) (3rd generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---3rd-generation-)
Apple TV (com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p)
Apple TV 4K (com.apple.CoreSimulator.SimDeviceType.Apple-TV-4K-4K)
Apple TV 4K (at 1080p) (com.apple.CoreSimulator.SimDeviceType.Apple-TV-4K-1080p)
Apple Watch - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm)
Apple Watch - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm)
Apple Watch Series 2 - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-38mm)
Apple Watch Series 2 - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-42mm)
Apple Watch Series 3 - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-3-38mm)
Apple Watch Series 3 - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-3-42mm)
Apple Watch Series 4 - 40mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-4-40mm)
Apple Watch Series 4 - 44mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-4-44mm)
== Runtimes ==
iOS 12.1 (12.1 - 16B91) - com.apple.CoreSimulator.SimRuntime.iOS-12-1 
iOS 12.2 (12.2 - 16E226) - com.apple.CoreSimulator.SimRuntime.iOS-12-2 
tvOS 12.2 (12.2 - 16L225) - com.apple.CoreSimulator.SimRuntime.tvOS-12-2 
watchOS 5.2 (5.2 - 16T224) - com.apple.CoreSimulator.SimRuntime.watchOS-5-2 
== Devices ==
-- iOS 12.1 --
    iPhone 5s (A6EE7783-0129-4FB0-B58F-50D6D80179AD) (Shutdown) 
    iPhone 6 (1A391BF6-EC94-42EA-A06D-D1420719F3B9) (Shutdown) 
    iPhone 6 Plus (C6E7BCE5-7E3D-4F94-A1CE-EE35EFF4D8E5) (Shutdown) 
    iPhone 6s (A7F8CE60-D0DB-4E7B-8FE4-2FEB0F029FDA) (Shutdown) 
    iPhone 6s Plus (85074E31-8AEF-4CCC-8FD6-7B5063014C52) (Shutdown) 
    iPhone 7 (3EA6C580-8428-4AE6-BA3B-D8702120DAAE) (Shutdown) 
    iPhone 7 Plus (49685908-E942-4E6E-850F-E4E23270ADEC) (Shutdown) 
    iPhone 8 (56EC4402-E062-496C-9757-B715018FC7D4) (Shutdown) 
    iPhone 8 Plus (83AE1A8D-EFAE-4CE9-95FB-09DA15A401B9) (Shutdown) 
    iPhone SE (2E716BFB-C67F-42DE-BB07-0E1937A21ECC) (Shutdown) 
    iPhone X (A3BD0C17-22EE-49B2-8A78-43BEFBA90347) (Shutdown) 
    iPhone XS (66C8994D-06EC-4F12-9C42-C5B793100E5E) (Shutdown) 
    iPhone XS Max (B9C0EEC0-D783-46A7-A883-BA7D089A4BB9) (Shutdown) 
    iPhone XR (7DFED74A-FFD3-4D84-BB4E-8869340CD23C) (Shutdown) 
    iPad Air (E7EBFE5B-2D96-43C9-92FD-D1C20D1D57BB) (Shutdown) 
    iPad Air 2 (46E0D053-113B-45EB-9464-29C97E8F4143) (Shutdown) 
    iPad (5th generation) (65A02B64-1FBA-45E0-BB9D-955D52328DC2) (Shutdown) 
    iPad Pro (9.7-inch) (79A43BF8-4817-4537-8EF3-87782FF977D1) (Shutdown) 
    iPad Pro (12.9-inch) (9F84BB0C-D4CE-4E5C-B863-3A178AC69D1A) (Shutdown) 
    iPad Pro (12.9-inch) (2nd generation) (8174144C-B2F2-4E29-8A01-58C433817042) (Shutdown) 
    iPad Pro (10.5-inch) (3D39A233-B564-4786-A9C4-8811CE8E92C3) (Shutdown) 
    iPad (6th generation) (09571543-B1BF-4863-82E2-C2EEBE83A17B) (Shutdown) 
    iPad Pro (11-inch) (2AF50A50-206E-4675-9D36-4180C12226D0) (Shutdown) 
    iPad Pro (12.9-inch) (3rd generation) (03CD19CB-DDBC-482E-92C1-852E8B8020F3) (Shutdown) 
-- iOS 12.2 --
    iPhone 5s (F6B43B46-49AB-4B8F-894F-0BD226C5A206) (Shutdown) 
    iPhone 6 (09981550-1FE6-4408-9E9E-8680D3F6460B) (Shutdown) 
    iPhone 6 Plus (06547005-A1FA-4D24-AFEA-9947ACDF1E97) (Shutdown) 
    iPhone 6s (7693EA87-82D7-4410-945E-0814249760F5) (Shutdown) 
    iPhone 6s Plus (5B412695-3327-4EEB-AA46-BC29A1D3672B) (Shutdown) 
    iPhone 7 (82207F25-EEFF-481C-9E01-F221911B8656) (Shutdown) 
    iPhone 7 Plus (2FC6822E-D4AC-47D9-9563-52EB4C73850C) (Shutdown) 
    iPhone 8 (53F90179-F6F2-459B-BA27-A7A2838D8128) (Shutdown) 
    iPhone 8 Plus (51467C5E-DA75-4808-8406-84A88A272420) (Shutdown) 
    iPhone SE (386197D0-E892-47F8-B20A-828A4CE37767) (Shutdown) 
    iPhone X (3BE7AAE6-8179-45A3-A3A9-47B39CB85CD4) (Shutdown) 
    iPhone Xs (97AD9B62-14C1-4B85-87F5-1228DBB0A2F4) (Shutdown) 
    iPhone Xs Max (03E616D3-C092-4C5D-A6FD-30B34C8DB682) (Shutdown) 
    iPhone Xʀ (6FBE4E6D-C996-4C12-8E53-382C0F676916) (Shutdown) 
    iPad Air (3rd generation) (47AD274A-D861-4536-8DBA-982B463BAD77) (Shutdown) 
    iPad Air (66638BC6-5231-48A1-8103-86EB09C174B0) (Shutdown) 
    iPad Air 2 (FA0B756F-0618-4A43-B595-E7337039152E) (Shutdown) 
    iPad (5th generation) (D76BC7EE-BD12-44F8-A731-79185E41F88F) (Shutdown) 
    iPad Pro (9.7-inch) (99658838-2297-4D2D-B0D0-4138CBE9D068) (Shutdown) 
    iPad Pro (12.9-inch) (12A7D873-8473-4B21-851A-31D2AD7A7EEB) (Shutdown) 
    iPad Pro (12.9-inch) (2nd generation) (63EAC997-7CE6-40EF-B523-205E12F405A3) (Shutdown) 
    iPad Pro (10.5-inch) (29A6EC49-7F33-4124-9802-EC92E4A7E437) (Shutdown) 
    iPad (6th generation) (6CA11FC2-C055-464A-997B-084931CBB00F) (Shutdown) 
    iPad Pro (11-inch) (9A682523-BE51-4603-9BDC-1181E035905E) (Shutdown) 
    iPad Pro (12.9-inch) (3rd generation) (3125372C-CE7E-468C-BD46-E7EC7E86B36D) (Shutdown) 
-- tvOS 12.2 --
    Apple TV (5F2D8C58-8220-4306-A59E-3A98E57E7CD7) (Shutdown) 
    Apple TV 4K (7B4722B8-2047-4E98-A9F5-B9B833818CB9) (Shutdown) 
    Apple TV 4K (at 1080p) (3BFCAD76-7202-401E-AF82-8BE7D5AA0BFF) (Shutdown) 
-- watchOS 5.2 --
    Apple Watch Series 2 - 38mm (7D860666-B2CE-40AA-A6A9-CC0463D8FBE4) (Shutdown) 
    Apple Watch Series 2 - 42mm (6F30D22E-6247-496A-8739-D283C448B5BC) (Shutdown) 
    Apple Watch Series 3 - 38mm (B49BA647-EC5D-4CDA-9D18-04E5985E2A2A) (Shutdown) 
    Apple Watch Series 3 - 42mm (F5676BAB-2CFF-4E24-A45E-51BC7EF70E28) (Shutdown) 
    Apple Watch Series 4 - 40mm (5D7E915A-B323-410A-BED0-D67F509743BE) (Shutdown) 
    Apple Watch Series 4 - 44mm (EB520F19-9E5E-41F3-9880-7FE9B42D5F0C) (Shutdown) 
== Device Pairs ==
E68BEE28-C810-4016-8DBF-4A94989AACC7 (active, disconnected)
    Watch: Apple Watch Series 4 - 40mm (5D7E915A-B323-410A-BED0-D67F509743BE) (Shutdown)
    Phone: iPhone Xs (97AD9B62-14C1-4B85-87F5-1228DBB0A2F4) (Shutdown)
952D5FD5-2BBC-481E-81C1-4FE5D200050F (active, disconnected)
    Watch: Apple Watch Series 4 - 44mm (EB520F19-9E5E-41F3-9880-7FE9B42D5F0C) (Shutdown)
    Phone: iPhone Xs Max (03E616D3-C092-4C5D-A6FD-30B34C8DB682) (Shutdown)
```

Environment:
- Xcode 10.2
- MacOS 10.14.4
- cocoapods (1.6.1)
- cocoapods-clean (0.0.1)
- cocoapods-core (1.6.1)
- cocoapods-deintegrate (1.0.4)
- cocoapods-downloader (1.2.2)
- cocoapods-plugins (1.0.0)
- cocoapods-search (1.0.0)
- cocoapods-stats (1.1.0)
- cocoapods-trunk (1.3.1)
- cocoapods-try (1.1.0)
- fourflusher (2.2.0)

**Comment by shywoody** [comment]
> 每当我跑，`pod spec lint`我得到这个输出：
> 
> ```
> ERROR | [iOS] unknown: Encountered an unknown error (Could not find a `ios` simulator (valid values: com.apple.coresimulator.simruntime.ios-12-1, com.apple.coresimulator.simruntime.ios-12-2, com.apple.coresimulator.simruntime.tvos-12-2, com.apple.coresimulator.simruntime.watchos-5-2). Ensure that Xcode -> Window -> Devices has at least one `ios` simulator listed or otherwise add one.) during validation.
> ```
> 虽然ios 12.2提供多种设备
> 
> ```
> $ xcrun simctl list
> == Device Types ==
> iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s)
> iPhone 5 (com.apple.CoreSimulator.SimDeviceType.iPhone-5)
> iPhone 5s (com.apple.CoreSimulator.SimDeviceType.iPhone-5s)
> iPhone 6 (com.apple.CoreSimulator.SimDeviceType.iPhone-6)
> iPhone 6 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus)
> iPhone 6s (com.apple.CoreSimulator.SimDeviceType.iPhone-6s)
> iPhone 6s Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus)
> iPhone 7 (com.apple.CoreSimulator.SimDeviceType.iPhone-7)
> iPhone 7 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-7-Plus)
> iPhone 8 (com.apple.CoreSimulator.SimDeviceType.iPhone-8)
> iPhone 8 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-8-Plus)
> iPhone SE (com.apple.CoreSimulator.SimDeviceType.iPhone-SE)
> iPhone X (com.apple.CoreSimulator.SimDeviceType.iPhone-X)
> iPhone Xs (com.apple.CoreSimulator.SimDeviceType.iPhone-XS)
> iPhone Xs Max (com.apple.CoreSimulator.SimDeviceType.iPhone-XS-Max)
> iPhone Xʀ (com.apple.CoreSimulator.SimDeviceType.iPhone-XR)
> iPad mini (5th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-mini--5th-generation-)
> iPad Air (3rd generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Air--3rd-generation-)
> iPad 2 (com.apple.CoreSimulator.SimDeviceType.iPad-2)
> iPad Retina (com.apple.CoreSimulator.SimDeviceType.iPad-Retina)
> iPad Air (com.apple.CoreSimulator.SimDeviceType.iPad-Air)
> iPad mini 2 (com.apple.CoreSimulator.SimDeviceType.iPad-mini-2)
> iPad mini 3 (com.apple.CoreSimulator.SimDeviceType.iPad-mini-3)
> iPad mini 4 (com.apple.CoreSimulator.SimDeviceType.iPad-mini-4)
> iPad Air 2 (com.apple.CoreSimulator.SimDeviceType.iPad-Air-2)
> iPad (5th generation) (com.apple.CoreSimulator.SimDeviceType.iPad--5th-generation-)
> iPad Pro (9.7-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--9-7-inch-)
> iPad Pro (12.9-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro)
> iPad Pro (12.9-inch) (2nd generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---2nd-generation-)
> iPad Pro (10.5-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--10-5-inch-)
> iPad (6th generation) (com.apple.CoreSimulator.SimDeviceType.iPad--6th-generation-)
> iPad Pro (11-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--11-inch-)
> iPad Pro (12.9-inch) (3rd generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---3rd-generation-)
> Apple TV (com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p)
> Apple TV 4K (com.apple.CoreSimulator.SimDeviceType.Apple-TV-4K-4K)
> Apple TV 4K (at 1080p) (com.apple.CoreSimulator.SimDeviceType.Apple-TV-4K-1080p)
> Apple Watch - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm)
> Apple Watch - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm)
> Apple Watch Series 2 - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-38mm)
> Apple Watch Series 2 - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-42mm)
> Apple Watch Series 3 - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-3-38mm)
> Apple Watch Series 3 - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-3-42mm)
> Apple Watch Series 4 - 40mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-4-40mm)
> Apple Watch Series 4 - 44mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-4-44mm)
> == Runtimes ==
> iOS 12.1 (12.1 - 16B91) - com.apple.CoreSimulator.SimRuntime.iOS-12-1 
> iOS 12.2 (12.2 - 16E226) - com.apple.CoreSimulator.SimRuntime.iOS-12-2 
> tvOS 12.2 (12.2 - 16L225) - com.apple.CoreSimulator.SimRuntime.tvOS-12-2 
> watchOS 5.2 (5.2 - 16T224) - com.apple.CoreSimulator.SimRuntime.watchOS-5-2 
> == Devices ==
> -- iOS 12.1 --
>     iPhone 5s (A6EE7783-0129-4FB0-B58F-50D6D80179AD) (Shutdown) 
>     iPhone 6 (1A391BF6-EC94-42EA-A06D-D1420719F3B9) (Shutdown) 
>     iPhone 6 Plus (C6E7BCE5-7E3D-4F94-A1CE-EE35EFF4D8E5) (Shutdown) 
>     iPhone 6s (A7F8CE60-D0DB-4E7B-8FE4-2FEB0F029FDA) (Shutdown) 
>     iPhone 6s Plus (85074E31-8AEF-4CCC-8FD6-7B5063014C52) (Shutdown) 
>     iPhone 7 (3EA6C580-8428-4AE6-BA3B-D8702120DAAE) (Shutdown) 
>     iPhone 7 Plus (49685908-E942-4E6E-850F-E4E23270ADEC) (Shutdown) 
>     iPhone 8 (56EC4402-E062-496C-9757-B715018FC7D4) (Shutdown) 
>     iPhone 8 Plus (83AE1A8D-EFAE-4CE9-95FB-09DA15A401B9) (Shutdown) 
>     iPhone SE (2E716BFB-C67F-42DE-BB07-0E1937A21ECC) (Shutdown) 
>     iPhone X (A3BD0C17-22EE-49B2-8A78-43BEFBA90347) (Shutdown) 
>     iPhone XS (66C8994D-06EC-4F12-9C42-C5B793100E5E) (Shutdown) 
>     iPhone XS Max (B9C0EEC0-D783-46A7-A883-BA7D089A4BB9) (Shutdown) 
>     iPhone XR (7DFED74A-FFD3-4D84-BB4E-8869340CD23C) (Shutdown) 
>     iPad Air (E7EBFE5B-2D96-43C9-92FD-D1C20D1D57BB) (Shutdown) 
>     iPad Air 2 (46E0D053-113B-45EB-9464-29C97E8F4143) (Shutdown) 
>     iPad (5th generation) (65A02B64-1FBA-45E0-BB9D-955D52328DC2) (Shutdown) 
>     iPad Pro (9.7-inch) (79A43BF8-4817-4537-8EF3-87782FF977D1) (Shutdown) 
>     iPad Pro (12.9-inch) (9F84BB0C-D4CE-4E5C-B863-3A178AC69D1A) (Shutdown) 
>     iPad Pro (12.9-inch) (2nd generation) (8174144C-B2F2-4E29-8A01-58C433817042) (Shutdown) 
>     iPad Pro (10.5-inch) (3D39A233-B564-4786-A9C4-8811CE8E92C3) (Shutdown) 
>     iPad (6th generation) (09571543-B1BF-4863-82E2-C2EEBE83A17B) (Shutdown) 
>     iPad Pro (11-inch) (2AF50A50-206E-4675-9D36-4180C12226D0) (Shutdown) 
>     iPad Pro (12.9-inch) (3rd generation) (03CD19CB-DDBC-482E-92C1-852E8B8020F3) (Shutdown) 
> -- iOS 12.2 --
>     iPhone 5s (F6B43B46-49AB-4B8F-894F-0BD226C5A206) (Shutdown) 
>     iPhone 6 (09981550-1FE6-4408-9E9E-8680D3F6460B) (Shutdown) 
>     iPhone 6 Plus (06547005-A1FA-4D24-AFEA-9947ACDF1E97) (Shutdown) 
>     iPhone 6s (7693EA87-82D7-4410-945E-0814249760F5) (Shutdown) 
>     iPhone 6s Plus (5B412695-3327-4EEB-AA46-BC29A1D3672B) (Shutdown) 
>     iPhone 7 (82207F25-EEFF-481C-9E01-F221911B8656) (Shutdown) 
>     iPhone 7 Plus (2FC6822E-D4AC-47D9-9563-52EB4C73850C) (Shutdown) 
>     iPhone 8 (53F90179-F6F2-459B-BA27-A7A2838D8128) (Shutdown) 
>     iPhone 8 Plus (51467C5E-DA75-4808-8406-84A88A272420) (Shutdown) 
>     iPhone SE (386197D0-E892-47F8-B20A-828A4CE37767) (Shutdown) 
>     iPhone X (3BE7AAE6-8179-45A3-A3A9-47B39CB85CD4) (Shutdown) 
>     iPhone Xs (97AD9B62-14C1-4B85-87F5-1228DBB0A2F4) (Shutdown) 
>     iPhone Xs Max (03E616D3-C092-4C5D-A6FD-30B34C8DB682) (Shutdown) 
>     iPhone Xʀ (6FBE4E6D-C996-4C12-8E53-382C0F676916) (Shutdown) 
>     iPad Air (3rd generation) (47AD274A-D861-4536-8DBA-982B463BAD77) (Shutdown) 
>     iPad Air (66638BC6-5231-48A1-8103-86EB09C174B0) (Shutdown) 
>     iPad Air 2 (FA0B756F-0618-4A43-B595-E7337039152E) (Shutdown) 
>     iPad (5th generation) (D76BC7EE-BD12-44F8-A731-79185E41F88F) (Shutdown) 
>     iPad Pro (9.7-inch) (99658838-2297-4D2D-B0D0-4138CBE9D068) (Shutdown) 
>     iPad Pro (12.9-inch) (12A7D873-8473-4B21-851A-31D2AD7A7EEB) (Shutdown) 
>     iPad Pro (12.9-inch) (2nd generation) (63EAC997-7CE6-40EF-B523-205E12F405A3) (Shutdown) 
>     iPad Pro (10.5-inch) (29A6EC49-7F33-4124-9802-EC92E4A7E437) (Shutdown) 
>     iPad (6th generation) (6CA11FC2-C055-464A-997B-084931CBB00F) (Shutdown) 
>     iPad Pro (11-inch) (9A682523-BE51-4603-9BDC-1181E035905E) (Shutdown) 
>     iPad Pro (12.9-inch) (3rd generation) (3125372C-CE7E-468C-BD46-E7EC7E86B36D) (Shutdown) 
> -- tvOS 12.2 --
>     Apple TV (5F2D8C58-8220-4306-A59E-3A98E57E7CD7) (Shutdown) 
>     Apple TV 4K (7B4722B8-2047-4E98-A9F5-B9B833818CB9) (Shutdown) 
>     Apple TV 4K (at 1080p) (3BFCAD76-7202-401E-AF82-8BE7D5AA0BFF) (Shutdown) 
> -- watchOS 5.2 --
>     Apple Watch Series 2 - 38mm (7D860666-B2CE-40AA-A6A9-CC0463D8FBE4) (Shutdown) 
>     Apple Watch Series 2 - 42mm (6F30D22E-6247-496A-8739-D283C448B5BC) (Shutdown) 
>     Apple Watch Series 3 - 38mm (B49BA647-EC5D-4CDA-9D18-04E5985E2A2A) (Shutdown) 
>     Apple Watch Series 3 - 42mm (F5676BAB-2CFF-4E24-A45E-51BC7EF70E28) (Shutdown) 
>     Apple Watch Series 4 - 40mm (5D7E915A-B323-410A-BED0-D67F509743BE) (Shutdown) 
>     Apple Watch Series 4 - 44mm (EB520F19-9E5E-41F3-9880-7FE9B42D5F0C) (Shutdown) 
> == Device Pairs ==
> E68BEE28-C810-4016-8DBF-4A94989AACC7 (active, disconnected)
>     Watch: Apple Watch Series 4 - 40mm (5D7E915A-B323-410A-BED0-D67F509743BE) (Shutdown)
>     Phone: iPhone Xs (97AD9B62-14C1-4B85-87F5-1228DBB0A2F4) (Shutdown)
> 952D5FD5-2BBC-481E-81C1-4FE5D200050F (active, disconnected)
>     Watch: Apple Watch Series 4 - 44mm (EB520F19-9E5E-41F3-9880-7FE9B42D5F0C) (Shutdown)
>     Phone: iPhone Xs Max (03E616D3-C092-4C5D-A6FD-30B34C8DB682) (Shutdown)
> ```
> 环境：
> 
> * Xcode 10.2
> * MacOS 10.14.4
> * cocoapods（1.6.1）
> * cocoapods-clean（0.0.1）
> * cocoapods-core（1.6.1）
> * cocoapods-deintegrate（1.0.4）
> * cocoapods-downloader（1.2.2）
> * cocoapods-plugins（1.0.0）
> * cocoapods-search（1.0.0）
> * cocoapods-stats（1.1.0）
> * cocoapods-trunk（1.3.1）
> * cocoapods-try（1.1.0）
> * fourflusher（2.2.0）

do you solve this problem,we met the same evil

**Comment by stefanrenne** [comment]
Spend Friday all day on this issue, no fix yet. Could use some support.

**Comment by shywoody** [comment]
> Spend Friday all day on this issue, no fix yet. Could use some support.

https://github.com/CocoaPods/CocoaPods/issues/8458 hope you get some support,run older Xcode version berfore 10.0 may be a solution

**Comment by stefanrenne** [comment]
Thats an old issue, which has been released in `fourflusher 2.2.0` but doesn't work on my machine ;)

**Comment by shywoody** [comment]
> Thats an old issue, which has been released in `fourflusher 2.2.0` but doesn't work on my machine ;)

orz....

**Comment by shywoody** [comment]
> Thats an old issue, which has been released in `fourflusher 2.2.0` but doesn't work on my machine ;)

i tried to update cocoapods version to 1.6.0 and gem fourflusher 2.2.0  ,it fixed my trouble,hope support you

**Comment by devmaximilian** [comment]
Running `gem install cocoapods` and `brew upgrade cocoapods` solved it for me. Gem version was 1.5.3 and brew version was 1.6.1

**Comment by stefanrenne** [comment]
See my ticket, I was already on 1.6.1

**Comment by pengGitHubUp** [comment]
I update the pod version to 1.6.1 and solved it. The old version was 1.5.0.

**Comment by VinutaPrabhu** [comment]
The issue was resolved on updating Cocoapods version. I was on 1.5.3 and on update my Cocoapods version is 1.6.2

**Comment by tguidon** [comment]
I am having this same issue with Cocoaposda 1.6.1 and 1.7.3. The Fourflusher upgrade does not fix this for me.

**Comment by shixiaoda** [comment]
I am having this same issue with Cocoaposda 1.7.1. The Fourflusher upgrade does not fix this for me.
And I installed Xcode 11

**Comment by tguidon** [comment]
I dug into this more and was able to fix this, but it feels a little hacky.

I also have Xcode 11 installed. It turns out I had to set the command line tools in both Xcode 10.2 and Xcode 11 to the Xcode 10.2 version. I seems like the wrong version of Xcode is used if both are not set to the 10.2 version.

**Comment by dnkoutso** [comment]
do folks use latest version of Fourflusher gem? Seems like it can handle Xcode 11 sims too.

**Comment by aiononhiii** [comment]
通过pod spec lint 检查命令报这个错误。
原因是：我的电脑是128G的，硬盘不足，我把/Users/jiaguoshang/Library/Developer/CoreSimulator/Devices文件夹下的所有模拟器文件都给宰了（当然你把/Users/jiaguoshang/Library/Developer/Xcode/Archives文件夹下的所有文件删除也能增加很多空间，我把这个文件下的文件删除了还是不空间不足。把/Users/jiaguoshang/Library/Developer/Xcode/DerivedData文件夹下的文件都删除。空间增加不少。重新联调真机就比较慢了，需要重新生成对应的设备文件），这样能省很多空间。你的xcode工程没有一个模拟器。
解决方案：xcode 下载一个模拟器。然后重新 pod spec lint

**Comment by aiononhiii** [comment]
通过 pod spec lint 检查命令报这个错误
原因是：我的电脑是128G的，硬盘不足，我把/Users/apple/Library/Developer/CoreSimulator/Devices文件夹下的所有模拟器文件都给删了, 于是 xcode 编译器没有一个模拟器,导致了这个错误
解决方案：xcode 下载一个模拟器（Xcode Download a simulator）然后重新检查 pod spec lint
